# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_system', '0004_auto_20161113_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterProduct'),
        ),
        migrations.AlterField(
            model_name='item',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_and_process.MasterService'),
        ),
    ]
