# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_system', '0005_auto_20161113_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='item',
        ),
    ]
