# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_system', '0006_remove_production_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
